# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birthday',
            field=models.CharField(default='2016-07-07', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='country',
            field=models.CharField(default='China', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(default='1111111111', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='username', max_length=200),
        ),
    ]
