# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0002_auto_20160714_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birthday',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
