# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0004_auto_20160714_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birthday',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.TextField(max_length=64),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.TextField(max_length=100),
        ),
    ]
