# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0005_auto_20160715_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
