# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0006_users_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='head',
            field=models.FileField(default='/static/images/user.jpg', upload_to='/static/upload/head'),
        ),
    ]
