# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0008_auto_20160716_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='head',
            field=models.ImageField(default='./static/images/user.jpg', upload_to='./static/upload/head'),
        ),
    ]
