# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0009_auto_20160716_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_online',
            field=models.BooleanField(default=False, max_length=1),
        ),
    ]
