# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0012_auto_20160720_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birthday',
            field=models.TextField(default='2016/07/22', max_length=100),
        ),
    ]
