# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Multimedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersvideo',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
        migrations.AddField(
            model_name='usersvideo',
            name='title',
            field=models.TextField(default='video', max_length=100),
        ),
        migrations.AddField(
            model_name='usersvideo',
            name='type',
            field=models.CharField(default='video', max_length=20),
        ),
    ]
