# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multimedia', '0002_auto_20160720_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersvideo',
            name='videos',
            field=models.FileField(default='./static/images/user.jpg', upload_to='./static/upload/videos'),
        ),
    ]
