# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0002_comment_postcontent_t_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashBoard',
        ),
    ]
