# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 02:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0003_delete_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='email',
            field=models.EmailField(default=datetime.datetime(2016, 7, 5, 2, 49, 32, 419091, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
