# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0004_auto_20160705_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='postcontent',
            name='date',
        ),
        migrations.RemoveField(
            model_name='t_comment',
            name='date',
        ),
    ]
