# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0005_auto_20160705_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updateuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, null=True)),
                ('birthday', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
