# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0007_auto_20160714_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateuser',
            name='phone',
            field=models.CharField(default='1111111111', max_length=200),
        ),
    ]
