# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0009_delete_updateuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('title', models.TextField(max_length=250)),
            ],
        ),
    ]
