# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0010_postblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='date',
            field=models.TextField(default='2016-01-01', max_length=100),
        ),
    ]
