# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0011_postcontent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontent',
            name='date',
            field=models.TextField(default='2016-01-01 14:22:22', max_length=100),
        ),
    ]
