# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0012_auto_20160716_0947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostBlog',
        ),
        migrations.AddField(
            model_name='postcontent',
            name='title',
            field=models.TextField(default='', max_length=250),
        ),
    ]
