# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0014_auto_20160722_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
