# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0020_postcontent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontent',
            name='image',
            field=models.ImageField(default='./static/images/user.jpg', upload_to='./static/upload/post/2016-07-23 12:37:14'),
        ),
    ]
