# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.Users'),
            preserve_default=False,
        ),
    ]
