# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_person_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person',
        ),
    ]
