# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20160509_0300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
