# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.IntegerField(verbose_name='注册人数')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
        ),
    ]
