# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
