# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_auto_20160711_0202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
