# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FriendSystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFriends',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='time',
        ),
        migrations.AddField(
            model_name='friends',
            name='friends',
            field=models.TextField(default=[]),
        ),
    ]
