# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FriendSystem', '0002_auto_20160716_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMeaasge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='friends',
            name='friends',
        ),
    ]
