# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FriendSystem', '0004_addmeaasge_meaasge'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmeaasge',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
