# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FriendSystem', '0005_addmeaasge_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddMeaasge',
            new_name='AddMessage',
        ),
    ]
