# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FriendSystem', '0006_auto_20160716_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmessage',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
