# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FriendSystem', '0007_auto_20160716_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmessage',
            name='meaasge',
            field=models.TextField(default='[]'),
        ),
    ]
