# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FriendSystem', '0009_auto_20160717_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='email',
            field=models.EmailField(default='x@xx.com', max_length=100),
        ),
    ]
