# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FriendSystem', '0013_auto_20160718_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmessage',
            name='disagree',
            field=models.TextField(default='[]'),
        ),
    ]
