# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FriendSystem', '0014_auto_20160718_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmessage',
            old_name='disagree',
            new_name='dismessage',
        ),
    ]
