# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FriendSystem', '0017_auto_20160718_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmessage',
            name='disagree',
        ),
    ]
