# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FriendSystem', '0019_addmessage_disagree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmessage',
            old_name='meaasge',
            new_name='message',
        ),
    ]
