# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FriendSystem', '0020_auto_20160718_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('email_to', models.EmailField(max_length=100)),
                ('content', models.TextField(default='')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
            ],
        ),
    ]
