# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FriendSystem', '0022_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room',
            field=models.TextField(default='[]'),
        ),
    ]
