# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FriendSystem', '0023_chatroom_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
